[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
evm_version = "cancun"

[rpc_endpoints]
mantle_testnet = "https://rpc.sepolia.mantle.xyz"

[etherscan]
mantle_testnet = { key = "${MANTLE_ETHERSCAN_API_KEY}", url = "https://api.routescan.io/v2/network/testnet/evm/5003/etherscan" }
